config/routes.rb
Rails.application.routes.draw do
  # ログイン&登録画面
  root to: 'welcome#index'
  get '/welcome', to: 'welcome#index'

  get '/about', to: 'welcome#about'

  # デバイスの設定
  devise_for :users, :controllers => {
     :registrations => 'users/registrations',
     :sessions => 'users/sessions'
  }

  authenticated :user do # ログインしないとアクセスできない設定

    resources :users, only: [:update, :edit]

    resources :calender, only: [:show] do
      resources :todos, except: [:index, :edit]
    end

    # 検索画面の表示
    get '/posts/search_list', to: 'posts#search_list'
    # 検索結果を非同期で出力させる
    get '/posts/search', to: 'posts#search'

    resources :posts

    # todo_list を作成するため
    get '/todos/search', to: 'todos#search'

    # 退会手続き画面
    get '/destroy_confirm', to: 'users#destroy_confirm', as: :user_destroy_confirm

    # パスワード変更
    resources :passwords, only: [:update, :edit]
  end
end

app/models/todo.rb
class Todo < ApplicationRecord
  # relation
  belongs_to :user

  # image upload
  mount_uploader :image, ImagesUploader

  # categoryの設定
  enum category: { work: 0, prive: 1 }

  # 日付は空でないこと
  validates :day, presence: true

  # todolistの検索
  scope :user_todo_list, -> (user_id,search_day) {
    where(user_id: "#{user_id}").where(day: "#{search_day}")
  }
  # todolistを時間をもとに昇順に並べる
  scope :order_todo_list, ->  {
    order(:start_time).order(:end_time)
  }
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  # 投稿者のみ自身の情報を編集、更新できる
  before_action :todo_correct_user, only: [:edit, :update, :destroy]

  def new
    @todo  = Todo.new
    @todo.category  = "work" #radio_buttonの初期値
    @todos = Todo.where(user_id: current_user.id)
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.user_id = current_user.id
    search_day = todo_params[:day]

    if @todo.save
      #todo_listの抽出
      @todos = Todo.user_todo_list(current_user.id, search_day).order_todo_list
      respond_to do |format|
        format.js
      end
    end
  end

  # 入力フォームの日付を変えると非同期で検索結果を返す
  def search
    @todos = Todo.where(user_id: current_user.id).where('day LIKE(?)', "%#{params[:keyword]}%").order_todo_list
    respond_to do |format|
      format.json { render 'calender#show', json: @todos }
    end
  end

  def show
    @todo_show = Todo.where(user_id: params[:calender_id]).where(id: params[:keyword])
  end

  def update
    @todo = Todo.find(params[:calender_id])
    @search_day = todo_params[:day] #todoリストのタイトルを変えるためインスタンス変数

    if @todo.update(todo_params)
      #todo_listの抽出
      @todos = Todo.user_todo_list(current_user.id, @search_day).order_todo_list
      respond_to do |format|
        format.js
      end
    end
  end

  def destroy
    @todo = Todo.find(params[:calender_id])
    search_day = @todo.day

    if @todo.destroy
      #todo_listの抽出
      @todos = Todo.user_todo_list(current_user.id, search_day).order_todo_list
      respond_to do |format|
        format.js
      end
    end
  end

  private

  def todo_params
    params.require(:todo).permit(:id, :user_id, :day, :title, :start_time, :end_time, :category, :content, :image)
  end

  def todo_correct_user
    todo_user = Todo.find(params[:calender_id]).user
    unless todo_user == current_user
      redirect_to calender_path(current_user)
    end
  end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/_new.html.slim
h2.todo_new_title 新規作成

= form_with model: @todo, url: calender_todos_path(params[:id]), class: "validate_field", id: "new_todo" do |form|
  .form-group
    = form.label :day, '日付'
    = form.date_field :day, value: Time.now.strftime("%Y-%m-%d"), class: 'form-control'

  .row
    .form-group.form-inline
      .col-sm-6
        = form.label :start_time, '開始時間'
        = form.text_field :start_time, class: 'form-control clear_field timepicker ml-2 mr-2'
      .col-sm-6
        = form.label :end_time, '終了時間'
        = form.text_field :end_time, class: 'form-control clear_field timepicker ml-2 mr-2'

  .form-group
    = form.label :title, 'タイトル'
    = form.text_field :title, class: 'form-control clear_field'

  .form-group.row.mt-4
    .col-sm-2
      = form.label :category, 'カテゴリ', {class: 'form-label'}
    .col-sm-10.btn-group
      label.btn.btn-outline-secondary[style="width:50%"]
        = form.radio_button :category, :work
        |  仕事
      label.btn.btn-outline-secondary[style="width:50%"]
        = form.radio_button :category, :prive
        |  私用

  .form-group
    = form.label :content, 'メモ'
    = form.text_area :content, class: 'form-control clear_field', rows:2

  = form.submit '登録する', class: 'todo_submit btn btn-primary mr-4 mb-4'

  .btn.btn-warning.mb-4.to_calender_btn
    | カレンダーへ

app/views/todos/_show.html.slim
h2.todo_show_title 詳細

.todo_show_content
 = form_with model: todo_show[0], url: calender_todo_path(todo_show[0].id), class: "validate_field", id: "show_todo" do |form|
   .form-group
     = form.label :day, '日付'
     = form.date_field :day, value: todo_show[0].day , class: 'form-control'

   .row
     .form-group.form-inline
       .col-sm-6
         = form.label :start_time, '開始時間'

          - if todo_show[0].start_time.nil?
            = form.text_field :start_time, value: "", class: 'form-control clear_field timepicker ml-2 mr-2'
          - else
            = form.text_field :start_time, value: todo_show[0].start_time.strftime("%H:%M"), class: 'form-control clear_field timepicker ml-2 mr-2'

       .col-sm-6
         = form.label :end_time, '終了時間'

          - if todo_show[0].end_time.nil?
            = form.text_field :end_time, value: "", class: 'form-control clear_field timepicker ml-2 mr-2'
          - else
            = form.text_field :end_time, value: todo_show[0].end_time.strftime("%H:%M"), class: 'form-control clear_field timepicker ml-2 mr-2'
   .form-group

     = form.label :title, 'タイトル'
     = form.text_field :title, class: 'form-control clear_field'

   .form-group.row.mt-4
     .col-sm-2
       = form.label :category, 'カテゴリ', {class: 'form-label'}
     .col-sm-10.btn-group
       label.btn.btn-outline-secondary[style="width:50%"]
         = form.radio_button :category, :work
         |  仕事
       label.btn.btn-outline-secondary[style="width:50%"]
         = form.radio_button :category, :prive
         |  私用

   .form-group
     = form.label :content, 'メモ'
     = form.text_area :content, class: 'form-control clear_field', rows:2

   = form.submit '更新する', class: 'todo_submit btn btn-primary mr-4 mb-4'

   .btn.btn-warning.mb-4.mr-4.to_calender_btn
     | カレンダーへ

   = link_to "削除する", calender_todo_path(todo_show[0].id), class: 'btn btn-danger mb-4', method: :delete, remote: true

app/views/todos/_todo_list.html.slim
= todos.each do |todo|
  tr.todo_row id="todo_#{todo.id}"
    td
      - if todo.start_time.blank?
          | -
      - else
        = todo.start_time.strftime("%H:%M")
    td
      - if todo.end_time.blank?
          | -
      - else
        = todo.end_time.strftime("%H:%M")
    td
      = todo.title

app/views/todos/create.js.erb
// todo listの初期化
$('#todo_search_result').find('tr').remove();
$('#todo_search_result').find('td').remove();

// todo listの非同期での追加
$("<%= escape_javascript(render partial: '/todos/todo_list', locals: { todos: @todos }) %>").appendTo("#todo_search_result");

// 日付以外の入力フォームのリセット
$(".clear_field").val("");

app/views/todos/destroy.js.erb
// 詳細ページの表示
$('.calendar_view').removeClass('is_hide');
$('.todos_new_form').addClass('is_hide');
$('.todo_show_view').addClass('is_hide');

// todo listの初期化
$('#todo_search_result').find('tr').remove();
$('#todo_search_result').find('td').remove();

// todo list
$("<%= escape_javascript(render partial: '/todos/todo_list', locals: { todos: @todos }) %>").appendTo("#todo_search_result");

app/views/todos/edit.html.slim
h1 Todos#edit
p Find me in app/views/todos/edit.html.slim

app/views/todos/show.js.erb
// 詳細ページの表示
$('.todo_show_view').removeClass('is_hide');
$('.todos_new_form').addClass('is_hide');
$('.calendar_view').addClass('is_hide');

// 前の詳細ページの内容を削除する
$('.todo_show_title').remove();
$('.todo_show_content').remove();

$("<%= escape_javascript(render partial: '/todos/show', locals: { todo_show: @todo_show }) %>").appendTo(".todo_show_view");

app/views/todos/update.js.erb
// todo listの初期化
$('#todo_search_result').find('tr').remove();
$('#todo_search_result').find('td').remove();

//todoリストのタイトルをアップデートした日にする
$('.table_title').text("<%= @search_day %>")

// todo listの非同期での追加
$("<%= escape_javascript(render partial: '/todos/todo_list', locals: { todos: @todos }) %>").appendTo("#todo_search_result");