config/routes.rb
Rails.application.routes.draw do
  # ログイン&登録画面
  root to: 'welcome#index'
  get '/welcome', to: 'welcome#index'

  get '/about', to: 'welcome#about'

  # デバイスの設定
  devise_for :users, :controllers => {
     :registrations => 'users/registrations',
     :sessions => 'users/sessions'
  }

  authenticated :user do # ログインしないとアクセスできない設定

    resources :users, only: [:update, :edit]

    resources :calender, only: [:show] do
      resources :todos, except: [:index, :edit]
    end

    # 検索画面の表示
    get '/posts/search_list', to: 'posts#search_list'
    # 検索結果を非同期で出力させる
    get '/posts/search', to: 'posts#search'

    resources :posts

    # todo_list を作成するため
    get '/todos/search', to: 'todos#search'

    # 退会手続き画面
    get '/destroy_confirm', to: 'users#destroy_confirm', as: :user_destroy_confirm

    # パスワード変更
    resources :passwords, only: [:update, :edit]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  # relation
  belongs_to :user

  # 日付は空でないこと
  validates :day, presence: true

  # postの検索
  scope :post_search, -> (search_params) do
     day_search(search_params[:day])
      .title_search(search_params[:title])
      .content_search(search_params[:content])
   end
  scope :day_search, -> (day)   {
     where(['day = ?', "#{day}"]) if day.present?
  }
  scope :title_search, -> (title)   {
     where(['title like ?', "%#{title}%"]) if title.present?
  }
  scope :content_search, -> (content)   {
     where(['content like ?', "%#{content}%"]) if content.present?
  }

  # todolistを時間をもとに昇順に並べる
  scope :order_todo_list, ->  {
    order(:start_time).order(:end_time)
  }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # 投稿者のみ自身の情報を編集、更新できる
  before_action :post_correct_user, only: [:edit, :update, :destroy]

  def index
    @posts = Post.where(user_id: params[:format]).order(day: "DESC").includes(:user)
    @user = User.find(params[:format])
  end

  def show
    @post = Post.find(params[:id])
    @todos = Todo.where(user_id: @post.user_id).where(day: @post.day).order_todo_list
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_params)
    post.user_id = current_user.id

    if post.save
      redirect_to post_path(post.id)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])

    if post.update(post_params)
      redirect_to post_path(post)
    else
      render :show
    end
  end

  def destroy
    post = Post.find(params[:id])

    if post.destroy
      redirect_to posts_path(current_user)
    else
      render :show
    end
  end

  def search_list
    # search_list.htmlを表示させる
  end

  # search_js.erbをレスポンスする
  def search
    @posts = Post.post_search(params).includes(:user)
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :day, :title, :content)
  end

  def post_correct_user
    post_user = Post.find(params[:id]).user
    unless post_user == current_user
      redirect_to calender_path(current_user)
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post_list.html.slim
table.table.mt-3
  thead.thead-light
    tr
      th ユーザ
      th 日付
      th タイトル
      th コメント
  tbody
    - posts.each do |post|
      tr.post_row data-href="/posts/#{post.id}"
        td
          - if post.user.image.blank?
            = image_tag "noimage.jpg", :size => '100x100', class: 'img-thumbnail rounded'
          - else
            = image_tag post.user.image.to_s, :size => '100x100', class: 'img-thunmbnail rounded'
        td
          = post.day
        td
          = post.title
        td
          = post.content

app/views/posts/_todo_list.html.slim
table#todo_lists.table
  h3 = post.day
  tbody
    - todos.each do |todo|
      tr.todo_row id="todo_#{todo.id}"
        td
          - if todo.start_time.blank?
              | -
          - else
            = todo.start_time.strftime("%H:%M")
        td
          - if todo.end_time.blank?
              | -
          - else
            = todo.end_time.strftime("%H:%M")
        td
          = todo.title

app/views/posts/edit.html.slim
.row#todo_post_check
  .col-sm-6
    h2.post_new_title 編集ページ
    = form_with model: @post, url: post_path, class: "validate_field", id: "new_post" do |form|

      .form-group
        = form.label :day, '日付'
        = form.date_field :day, class: 'form-control', id: 'todo_day';

      .form-group
        = form.label :title, 'タイトル'
        = form.text_field :title, class: 'form-control'

      .form-group
        = form.label :content, 'コメント'
        = form.text_area :content, class: 'form-control', rows:2

      .btn-group
        = form.submit '編集する', class: 'post_submit btn btn-primary mr-4'
        = link_to "キャンセル", posts_path(current_user.id), class: 'btn btn-warning'

  .col-sm-6
    table#todo_lists.table
      h3.table_title
      tbody#todo_search_result

app/views/posts/index.html.slim
.container
  .row
    .col-sm-4.post_profile_box
      .row
        .col-sm-6
          /プロフィール画像
          .post_profile_content
            - if @user.image.blank?
              = image_tag "noimage.jpg", :size => '150x150', class: 'img-thumbnail rounded'
            - else
              = image_tag @user.image.to_s, :size => '150x150', class: 'img-thumbnail rounded'

          /ユーザー名
          h5.post_profile_content.text-center.mt-2
            -if @user.name.blank?
              | no name
            -else
              = @user.name

        /プロフィール文
        .col-sm-6
          .post_profile_content
            -if @user.profile.blank?
              | no_message
            -else
              = @user.profile

    - if @user == current_user
      .col-sm-8.to_new_post.align-self-center
        .row.justify-content-center
          = link_to "投稿ページへ", new_post_path(current_user.id), class: 'btn btn-primary'

.container
  .post_todo_list
    = render partial: "posts/post_list", locals: { posts: @posts }

app/views/posts/new.html.slim
.row#todo_first_check
  .col-sm-6
    h2.post_new_title 投稿ページ
    = form_with model: @post, url: posts_path(current_user.id), class: "validate_field", id: "new_post" do |form|

      .form-group
        = form.label :day, '日付'
        = form.date_field :day, value: Time.now.strftime("%Y-%m-%d"), class: 'form-control', id: 'todo_day';

      .form-group
        = form.label :title, 'タイトル'
        = form.text_field :title, class: 'form-control'

      .form-group
        = form.label :content, 'コメント'
        = form.text_area :content, class: 'form-control', rows:2

      .btn-group
      = form.submit '投稿する', class: 'post_submit btn btn-primary mr-4'
      = link_to "キャンセル", posts_path(current_user.id), class: 'btn btn-warning'

  .col-sm-6
    table#todo_lists.table
      h3.table_title
      tbody#todo_search_result

app/views/posts/search.js.erb
// post listの初期化
$('#post_search_result').find('table').remove();

// post listの非同期での追加
$("<%= escape_javascript(render partial: '/posts/post_list', locals: { posts: @posts }) %>").appendTo("#post_search_result");

app/views/posts/search_list.html.slim
.container
  h2 検索ページ

  /検索フォーム
  #post_search_form.form-row
    .form-group.col-sm-3
      span 日付
      br
      input.post_search_input.post_search_day[type="date" name="keyword"]
    .form-group.col-sm-3
      span タイトル
      input.post_search_input.post_search_title[type="text" name="keyword"]
    .form-group.col-sm-3
      span コメント
      input.post_search_input.post_search_content[type="text" name="keyword"]


/検索結果の表示 search.js.erbが結果をappendする
.container
    #post_search_result
      table.table.mt-3
        thead.thead-light
          tr
            th ユーザ
            th 日付
            th タイトル
            th コメント

app/views/posts/show.html.slim
.row
  .col-sm-6
    h2.post_show_title 投稿ページ
    .post_show_form
      label 日付
      p.post_day.bg-white.border = @post.day

    .post_show_form
      label タイトル
      p.post_title.bg-white.border = @post.title

    .post_show_form
      label コメント
      p.post_content.bg-white.border = @post.content

    - if @post.user_id == current_user.id
      .btn-group.mt-3
        = link_to "編集する", edit_post_path(@post), class: 'btn btn-primary'
        = link_to "一覧に戻る", posts_path(current_user.id), class: 'btn btn-warning mr-2 ml-2'
        = link_to "削除する", post_path(@post), class: 'btn btn-danger', method: :delete, remote: true
    - else
      .btn-group.mt-3
        = link_to "検索画面へ", posts_search_list_path, class: 'btn btn-primary'
        = link_to "このユーザの投稿一覧へ", posts_path(@post.user_id), class: 'btn btn-warning mr-2 ml-2'
        = link_to "カレンダーへ", calender_path(current_user.id), class: 'btn btn-info'

  .col-sm-6
    = render partial: "posts/todo_list", locals: { todos: @todos, post: @post }