config/routes.rb
Rails.application.routes.draw do
  # ログイン&登録画面
  root to: 'welcome#index'
  get '/welcome', to: 'welcome#index'

  get '/about', to: 'welcome#about'

  # デバイスの設定
  devise_for :users, :controllers => {
     :registrations => 'users/registrations',
     :sessions => 'users/sessions'
  }

  authenticated :user do # ログインしないとアクセスできない設定

    resources :users, only: [:update, :edit]

    resources :calender, only: [:show] do
      resources :todos, except: [:index, :edit]
    end

    # 検索画面の表示
    get '/posts/search_list', to: 'posts#search_list'
    # 検索結果を非同期で出力させる
    get '/posts/search', to: 'posts#search'

    resources :posts

    # todo_list を作成するため
    get '/todos/search', to: 'todos#search'

    # 退会手続き画面
    get '/destroy_confirm', to: 'users#destroy_confirm', as: :user_destroy_confirm

    # パスワード変更
    resources :passwords, only: [:update, :edit]
  end
end

app/views/layouts/_error_message.html.slim
- if flash[:error]
  .alert.alert-danger
    = flash[:error]
    button.close[type="button" data-dismiss="alert" aria-label="閉じる"]
      span[aria-hidden="true"]
        | ×

- if flash[:notise]
  .alert.alert-success.alert-dismissible.fade.show
    = flash[:notise]
    button.close[type="button" data-dismiss="alert" aria-label="閉じる"]
      span[aria-hidden="true"]
        | ×

app/views/layouts/_footer.html.slim
footer.page-footer
  .footer-copyright.text-center.py-3
    | © 2019 Copyright: calcal

app/views/layouts/_header.html.slim
nav.navbar.navbar-light.navbar-expand-md.nav-color
  .container

    /ログインした場合
    - if user_signed_in?
      /logo
      = link_to "CalCal", calender_path(current_user)

      ul.navbar-nav.ml-auto
        li.nav-item
          = link_to "投稿検索", posts_search_list_path, class: "fa fa-search mr-2"

        /サイドメニューの表示
        button.nav-item.drawer-toggle.drawer-hamburger[type="button"]
          span.sr-only
            | toggle navigation
          span.text-primary
            = fa_icon "user", text: "プロフィール"
        == render "layouts/usermenu"

    /ログインしていない場合
    - else
      /logo
      = link_to "CalCal", root_path

      ul.navbar-nav.ml-auto
        li.nav-item
          = link_to "about", about_path

app/views/layouts/_setting.html.slim
ul.list-group.mt-3
  = link_to edit_user_path(current_user)
    li.list-group-item.list-group-item-action
      | プロフィール編集

  = link_to edit_password_path(current_user) do
    li.list-group-item.list-group-item-action
      | パスワード変更

  = link_to user_destroy_confirm_path(current_user) do
    li.list-group-item.list-group-item-action
      | 退会手続き

app/views/layouts/_usermenu.html.slim
nav.drawer-nav
  ul.drawer-menu

    /プロフィール画像
    .text-center.mt-3.mb-3
      - if current_user.image.blank?
        = image_tag "noimage.jpg", :size => '100x100', class: 'img-thumbnail rounded'
      - else
        = image_tag current_user.image.to_s, :size => '100x100', class: 'img-thunbnail rounded'

    /ユーザー名
    h5.text-center
      -if current_user.name.blank?
        | no name
      -else
        = current_user.name

    li.drawer-menu-item
        = link_to "プロフィール設定", edit_user_path(current_user)

    li.drawer-menu-item
      a[href="#"]
        = link_to "投稿一覧", posts_path(current_user)

    li.drawer-menu-item
      = link_to "ログアウト", destroy_user_session_path, method: "delete"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | CalCal
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body.drawer.drawer--right
    #wrapper
      == render "layouts/header"

      == render "layouts/error_message"

      .container.mt-5
        = yield

      == render "layouts/footer"